branch-defaults:
  dev:
    environment: udacity-c2-restapi-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udacity-c2-restapi
  branch: null
  default_ec2_keyname: test-frankfurt
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udagram-dev1
  repository: null
  sc: git
  workspace_type: Application
